### ISSUE TITLE
Reversing a readonly tuple

### ISSUE THREAD

**Issue by reggi** [ksxnodemodules/typescript-tuple#17]
I have this tuple of functions and I am trying to reverse it.

```ts
    namespace Utils {
        export type IsFinite<Tuple extends any[], Finite, Infinite> = {
            empty: Finite
            nonEmpty: ((..._: Tuple) => any) extends ((_: infer First, ..._1: infer Rest) => any)
            ? IsFinite<Rest, Finite, Infinite>
            : never
            infinite: Infinite
        }[
            Tuple extends [] ? 'empty' :
            Tuple extends (infer Element)[] ?
            Element[] extends Tuple ?
            'infinite'
            : 'nonEmpty'
            : never
        ]

        export type Prepend<Tuple extends any[], Addend> =
            ((_: Addend, ..._1: Tuple) => any) extends ((..._: infer Result) => any) ? Result : never


        export type Reverse<Tuple extends any[], Prefix extends any[] = []> = {
            empty: Prefix,
            nonEmpty: ((..._: Tuple) => any) extends ((_: infer First, ..._1: infer Next) => any)
            ? Reverse<Next, Prepend<Prefix, First>>
            : never
            infinite: {
                ERROR: 'Cannot reverse an infinite tuple'
                CODENAME: 'InfiniteTuple'
            }
        }[
            Tuple extends [any, ...any[]]
            ? IsFinite<Tuple, 'nonEmpty', 'infinite'>
            : 'empty'
        ]
    }

    export type ReadFuncs = readonly ((x: any) => any)[]
    export type Reverse<Tuple extends ReadFuncs> = Utils.Reverse<Tuple>
```

[Playground](https://www.typescriptlang.org/play/?target=5&ssl=1&ssc=1&pln=38&pc=72#code/AQ4OwQwWwUwZwA4QMY2AVQC4EsA2dgBvAWAChQLgYAPBAewCdNhMBPBNASTgDFsxsmGAB4AKgFcEuNDSFgAJgQhhWAbQC6AGmB8BQ7ZzAAzfoJgA+YAF4iZSvapQEbAFw7TQuw4pg6YAKJOrsAAFCEAdJEA+m4SUjAAlNaWyqxJsjAKBGExwPxGMAzuDHCY2pHhUQCMbvmFwABK8JhJVikqCV7eIAD8wNy6ZsJNpdqD+v3GHhZd3W5gMABuhbPe+dNuhiZ6MKugAL6qe-Zx0lTUcorAGsB9AOQwQax3wC7HlKcyF5lXIXVF-mksDALRuPXeFEBj0ymBuGSywE+twhoDu6x2dxRIDcd18ASemPI3Wx4CWKyJ9nUZHeNHoTBY7DQAAUGDAOAoxJIzvCrqkNNoAILyeQ-SxWLGhEK5IUihTlaI1RFcxLJYCpdLfBFhCq5f6NeDiXAtVXq276uCG5jzMkMamkGm0RjMNgcfXLEoiJE8pQqfnAFkwEzUc6XH1qdTWa7qMW2CndR7OVhuANBzQSvGBRNubXRWLK1rtNIhn7ZKW1Yz1PglMrAHWKvUAOVkBbVHQlfSa7rgIibF20AfZ8mEKew1DG2Gr5nMEut7ol6LMbhIceJIH8DQaAHkGjiAMLKXzMVldtDKPJTHYsZWE1eUXebgAi-gbAoAsv4cVtpp8b6v9u9DglL1NSuVRUnlcI+XUKkVwcPoBmmTl4m0XE-EzNg7hQhchDuadYPsHEEww94YIof97TjWknQZV0mggeQeHEMBkAIGxWXovxcFYSVqDcU02lbNINFmKj6RdNBO0KbskO5ECCDohimJYmMsDwOBwkkj0ZIsIA)

**Comment by reggi** [comment]
I've made a couple of attempts to replace all of the `any[]` calls to `ReadFuncs` but it's not working.

**Comment by reggi** [comment]
Posted here: https://stackoverflow.com/questions/58925469/reverse-a-read-only-tuple

**Comment by KSXGitHub** [comment]
@reggi You did not add enough `readonly`.

[Playground](https://www.typescriptlang.org/play/?target=5#code/HYQwtgpgzgDiDGEAEBVALgSwDZSQbwFgAoJUpCADxgHsAnNJNATxmQEkoAxDYDNCADwAVAK4wsySv2AATXLQggZ1YFiZIQwJgG0AugBok3Xv0NtgAMx58IAPiQBefMTKvyYGMwBcR6-xdupMAqAKIe3kgAFJEAdHEA+j6i4hAAlI72mkzpUhCyuNGJSDwWELS+tFBohnEx8QCMPiVlSABK0GjpDplaqQGBAPxIHMY2Au1VhqOmw5Z+dv1uPsAQAG5li64l8z7mViYQiwC+2ptkyRLkFNJySApKKmpIekhDAOQQ4UxvSF5npBdJNc8rd7spVOpIs1yiEJJBgJ0XgN-ndFOCnrDPnk0C9cvkkIDXii3tsDm8UT43sFgGFPN8KUgVutaItdMRFpQaPRGCxkAAFBSsWTCMSXPGgtGPdRZPSGACCMhkIPsDhRhR8CqVshqCUaBNFaQyGl6VxuBViCSalhaExEWE6Rqy6SGtvtv0Zaw2RHZJDInLoDGYrDansqgkJ4vkkohxp0BiQAogVgoppBUYeMZlukcqIzTz0KucvsCnzpPkTyf0KOptIi0VqRUBXR62VT+PVxWt5W4lWqSAbeuhSAAclJm7G+sW3C7Q1BBKProZE0KZAIKxgKFMML3bLYGUyvYFSKSbD5CFOj0gQq1WgB5VqUgDCmmCDAUzLnxs7+xsjAN5IvI9H1vAAREJhzlABZEJKT2eZAQAy8jmOU5AIBA02wlPN1G0LIdRiLM2TQ15hi4eYRRSQwqVCL43iok9+DePdiMpUtmEQsgiOQ70iAAel4pAAAs0DQGAoC8fiAHM+EEkQACMYngagwF4gBrKAKGCJUwGoGQ7WgXig2geBaAwTwAFo0ANXiMCgKARAM+oAHYfX9bkjJDJROBEYB4FwJwwSlKJIgoHwnUdXo9GINzA15EMP3DDDI08mRvN8qBC3QbAoBidoEooiRmOIJTgCqK5wBSHNtEicc3kgagAHc6KiccAGZsxAXASqqH0PNWHM8rKOcBCM6gLHKjxCt6uKAA0c0CmNqtq+qmsMGqjXa4gPIANQG2dBBm2wgA). You can use `diff` command to know the changes that I made.

**Comment by KSXGitHub** [comment]
BTW, I can make changes to this very repo, but I am busy at the moment, so pull requests are welcomed.
