### ISSUE TITLE
[Feature]: Add "recursivePluck" (tuple as index type)

### ISSUE THREAD

**Issue by maximilianMairinger** [ksxnodemodules/typescript-tuple#20]
# Feature request

Ive recently been looking for ages to find a type-save implementation of recursively [plucking](https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types) an object via a tuple (explaination below). As I was unable to find any solution online, I resorted to posting a [stackoverflow](https://stackoverflow.com/questions/61044575/typescript-using-a-tuple-as-index-type) question which was answered brilliantly by @maciejsikora very recently. 

Would you be open to adopting this type here? Before diving in to the depths of the internet to find a solution for my problem, I was aware of `typescript-tuple` (searching `typescript-tuple` was actually the first thing I did when researching). Hence my request to adopt it here. I understand if you consider this off topic here, since it is not purely of tuple domain. If so, Id gald if you could point me in a direction (maybe another library) where this feature would be better suited.

```ts
type Test1 = RecursivePluck<{a: {b: {c: {e: string}}, d: string}}, ['a','d']> // typeof string
type Test2 = RecursivePluck<{a: {b: {c: string}, d: string}},['a', 'b']> // typeof {c: string}
```

Here the [implemantation](https://www.typescriptlang.org/play#code/C4TwDgpgBAqgdgZwBYEsBmwA8BBANFAFSggA9gI4ATBKbAJzoEMRNG4QA%20DqAWACgAvFAAUwxgC5a%20AHSyARpIIBKKAO5sQK0uSo1Rs6XQgIArgBtgklHDQQ6UAErHzwFWqgaVAfkfOLUSTgIADc7AG5%20UEgoAGVUDEwibQpqWgZmVnYuXkERYQMJQjd1di0yFL0xSQ0ZWSNTCysbO18G11USzSgfJzaAqCDQugi%20SPBoJyHgfigoROJy3TSmFg0OGah8XpcFnVT6FczOVSgAbQBdDfwAMRQ6BGBdisJTgGsIEAB7NEJzk4JTgAGS58WZbYyPZJLA4ZNYnOLoLAEbJCADeG1OAGkoNYoO8vj8COdJL1gKcAORmCgAc2ASHJfyhqUB3VgiHiWFu92A4La3BJITsWFJ%20HgyERmC5D15Lmy-AAvkCQWNogAZQVmE4sgA%20UAAjFBdQAmQ1QADMpoALKaAKwq6AAOW06tCZkwAA0nksXRAzNwhBtPUyaICNj49RtJEHFqkI6DWUbI1Bo3saIn4z4zUmU88sxmoJbs17UoX83b44FBXR%20PbfABjEz3FChAAKjDpmAA8nIAFbFmifXsQOs81o7YMedgXE4XfCq4L9qA%20zVCQH%20qDo%20NYnFwPEfb5Qbs94k5WazeeLwZ2DazHp%20abx2aSI9YxkxgdDkens8%20YTbCwUlScC0vSb6plALI%20Fe9gClMmD-sAHAqLqTgNk2rbtkgXa9q%20orshKmIyhYHD4E6ZDLpg85cDe-STEK8H3twKFVlgYocpghEIdRfCKviB5HsqfBRNABAQicqGNggzYQG2HaooUqIKBudaSA8dDWNS8r4JQqnAOpwHyvK6xCeMhAQiaQgSehMmYZg8mSIpDkqRuEC6fpmlaVAOlQGpGmGcZtZWVJGF0gAaowZgmBA2E9vgslIIucIBnwm6zNuuJ8T88UnjR8WJVOIJnqy8WvoumWHr2363lAJWUjSdIMouBo0T4L4lZi5yFWeApocFNlhRFUUxac7WdfgCIJPF3FFZWQw0bN148accAmAAtnIdiCcJZkPBalnDpJ0nxeFkXRfZG5Kaizm%20QZ2luX5WkUow5L4OScgMsZ22iQ81r7b1R2YSdQ3nY5ykOa5Pl6Q9d2Q%205hn4E9L3kpQH01nwAD06NQGg1hwBFIBQHS0BoCYcAjignxwPwJNk8AFO7kY-2tpFdavDFi6Dj2w6jnlE5BQDHZHlwwiDs%20vb4MAJhgFSkjxUoPWHSFSBA9FR5xZh3CpVAmM7lJlDQAAklAPYmA82MRWYciMKzhOfJOIAbFSjz1C41TsCcg4jLMaCfPYwhOzu%20skFAB6S9L0CMDQGgXCoWuzC7-hCAnZLWEHXXyhsRiS3QDP3iMGd8HWlNm4wJyM4rMks68wgg5dzmot55LBINEDkoZ8NnOSz24G9DIqDrnyvPwReII8chlwd1ktlXNcKXXDmN83p1t%203CNd0jrfnP3WN2HQvvD8Xjx1hPTOVyYrOzw588bovLcrx3iM9%209Peb9vxAMPvheH15J8V9P5-V1rk5Bekgm533bp5R%20vce51j7trLGg8D6j2IL-KeM8gFgxvqApeUV76QPXk-JGsDXooy3vAkOrwgA) by @maciejsikora.

**Comment by KSXGitHub** [comment]
> ```typescript
> type Test1 = RecursivePluck<{a: {b: {c: {e: string}}, d: string}}, ['a','d']> // typeof string
> ```

I don't understand the logic here. Did you mistype something?

> ```typescript
> type Test2 = RecursivePluck<{a: {b: {c: string}, d: string}},['a', 'b']> // typeof {c: string}
> ```

Why don't you just use index access twice (`type Test2 = ObjectType['a']['b']`)?

---

Anyway, this is indeed not of tuple domain. There is another package called `ts-toolbelt`, I think this utility would be more acceptable there.
