### ISSUE TITLE
warning typescript-tuple@2.1.0: The engine "typescript" appears to be invalid.

### ISSUE THREAD

**Issue by nnabinh** [ksxnodemodules/typescript-tuple#4]
> warning typescript-tuple@2.1.0: The engine "typescript" appears to be invalid.

Hi Khai, sorry minh khong co keyboard tieng Viet nen danh khong co dau.
Hien minh dang nhan warning vi this package dang su dung:

`"engines": {
    "typescript": "^3.0.0"
  }`

trong package.json

https://docs.npmjs.com/files/package.json#engines
thi minh thay khong nen dung typescript o day

**Comment by KSXGitHub** [comment]
Okay, I will fix this.

---

<details>
<summary>On a less important note,</summary>

> Hi Khai,

Proper mentioning is `@username` (i.e. `@KSXGitHub`, not `Khai`)

> sorry minh khong co keyboard tieng Viet nen danh khong co dau.

Web solutions are Google Translate, Google Docs, etc. Native solutions are UniKey on Windows, IBus on GNOME Linux, I don't know about KDE and macOS.

Also, I would like you to speak in English in GitHub even when you are talking to a fellow Vietnamese. It is to make the conversation accessible to everyone, not just the speakers of some unusual languages.
</details>

**Comment by KSXGitHub** [comment]
v2.1.1

**Comment by nnabinh** [comment]
I see. Thanks for the quick response.
